name: jornadadobem
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/jogoRoupas/
    - assets/images/jogoRoupas/calça/masculino/
    - assets/images/jogoRoupas/calça/feminino/
    - assets/images/jogoRoupas/camisa/masculino/
    - assets/images/jogoRoupas/camisa/feminino/
    - assets/images/jogoRoupas/shorts/
    - assets/images/jogoRoupas/vestido/
    - assets/images/jogoRoupas/sapato/masculino/
    - assets/images/jogoRoupas/sapato/feminino/
    - assets/images/jogoComidas/
    - assets/images/jogoComidas/alimentos/
    - assets/images/JogoColetarLixo/
    - assets/images/JogoColetarLixo/lixos/
    - assets/images/História/
    - assets/images/SimboloJogo/
    - assets/images/Créditos/
    - assets/images/ComoJogar/
